language: python

python:
  - "3.6"
  - "3.7"

branches:
  only:
    - master
    - dev

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION gdal scipy numpy shapely netCDF4 pytest
  - conda activate test-environment
  - python setup.py install

script:
- pytest -vv

deploy:
  provider: pypi
  user: enagel
  password:
    secure: hzNqwIlV0g56NV83+TJo0cLhDdSgQ6cgotFG+L5eWeh/OXVaGrosMPHxpn19czQp1OmN0N5bINzt9ew/FYug/eyhvBh+druJARRPdOm3ekiRTW2AGEh0m8U7ApETXUKX3teSX2O+vRDvJJC8zlVcmHcKij+yyKjQc2XXtizWWD4Xdqep0QBXfVIci38nDHkmb68NdsJsCNN2cJJozlqNh2LWd71Pl6NVyYLtiD3PFdhqlaVulflTyh96tALMRPPS9cZuoAOGrX7d1VyErBlr+7xoVP1ysdGGwqs6/lFoM3w3NP0Yj4iVPk7V4R2G7nxToeujQicMtbSwDJxqQ/706NV9dSpigmNS2129EfbcEomcyguYk7phNsx2m5S7yzVOffu3YmEBuB20nisTtI3E5+wdUbtf1PpPEtGIRmakPIFhfQT6IXAgGZEBfNc0K7ZzJ381kqCihpnFp4swH5uf6MrVrHDtwyALevfQqlAHZRakvdftw7VPPXfL6Kc6yn6rkUvfLYwRtbd8BtEVB1gYqdXIhJG3TARfkp9DThetlPAqqrctrfM8EYVTeDLN5tPo2pTgvYX1eYoFnxEXssjM5RkKVnpWitkXKEBdnrDQ1ijvUnDOuneLjMf5wOtPjhrJgzVyDDYLcDeNUxchxHVsPgY2WirBjDZGU2D9+SC/gxk=
  on:
    tags: true